---
- name: Automate Targat
  hosts: tag_name_ict_provisioner

  vars:
    aws_cli_path: '/usr/bin/aws'
    mw_id: {{ mv_id }}

  tasks:
    - name: Create target group
      shell: |            
        {{ aws_cli_path }}  ssm register-target-with-maintenance-window \
            --region us-east-1 \
            --window-id {{ mw_id }} \
            --name "Win_Testable_Target" \
            --resource-type "RESOURCE_GROUP" \
            --target "Key=resource-groups:Name,Values=RG_Win_Testable"                           
      register: target_output  