---
- name: Create Target Group
  hosts: tag_Name_ict_provisioner 

  vars:
    aws_cli_path: '/usr/bin/aws'
    mw_nm: "{{ mw_id }}"  

  tasks:
    - name: Create target group
      shell: |            
        {{ aws_cli_path }}  ssm register-target-with-maintenance-window \
            --region us-east-1 \
            --window-id {{ mw_nm }} \
            --name "Win_Testable_Target_test24" \
            --resource-type "RESOURCE_GROUP" \
            --target "Key=resource-groups:Name,Values=TestGrp1"                           
      register: target_output  
